### ISSUE TITLE
Did you give up on the project?

### ISSUE THREAD

**Issue by gravitacoes** [search5/Evernote-for-Linux#10]
I know Evernote has lost its way in recent years. Now it seems to have gotten better again. This is the best alternative to have Evernote working well on Linux and despite using an old version, it is the best alternative. Updates were fast and frequent with each officially released version, but it seems like you've given up. Could you talk a little about that?

**Comment by wokawoka** [comment]
I would also be very interested to know that.
Unfortunately evernote doesn't allow me anymore to log-in with the latest version published here, asking to upgrade the client ...
![image](https://github.com/search5/Evernote-for-Linux/assets/7824587/df4c9b84-57c4-49f4-b42e-3c102d874d39)

**Comment by gravitacoes** [comment]
I can still log in. Version 10.60.4. PopOS distro.

**Comment by wokawoka** [comment]
oh, on this machine I was running an old version (10.55.1 from Apr 3, 2023).
I upgraded to 10.60.4 and it now works.
Anyway this version was working until very recently, which means that if don't upgrade sooner or later they will block as well 10.60.4 :(
Thank you

**Comment by gravitacoes** [comment]
From what I understand, Evernote adopted RTL starting from version 10.60 and only higher versions are supported now, because of the new sync format. I believe that for this reason your version, which was 10.55, did not work. The API for Linux Beta versions has been disabled. As this project uses the Windows executable, it is the only way to run Evernote now.

**Comment by gravitacoes** [comment]
I tried to follow the instructions in this project to build the installer, but unfortunately I couldn't. It seems like it's outdated or my skill wasn't enough.

**Comment by wokawoka** [comment]
> oh, on this machine I was running an old version (10.55.1 from Apr 3, 2023). I upgraded to 10.60.4 and it now works. Anyway this version was working until very recently, which means that if don't upgrade sooner or later they will block as well 10.60.4 :( Thank you

Here we are, today evernote 10.60.4 is no more allowed to login :(

**Comment by search5** [comment]
@gravitacoes @wokawoka
When Vendingspoon acquired Evernote, they removed all Linux-specific support code that was included in the binaries for Windows.
As a result, it is no longer possible to repackage for Linux. We apologize that we are unable to support the project any longer.

**Comment by wokawoka** [comment]
> @gravitacoes @wokawoka When Vendingspoon acquired Evernote, they removed all Linux-specific support code that was included in the binaries for Windows. As a result, it is no longer possible to repackage for Linux. We apologize that we are unable to support the project any longer.

Thank you very much for the explanation.
Too bad they cut out linux completely. At this point there is no longer any excuse, it's time to migrate to the many other (better) alternatives (like obsidian).

I noticed that yesterday you initially archived this project (so that it was no more possible to even comment on the open issues), I'm very glad that you decided to unarchive it and to even explain to us how the situation actually is (so that, at this point, we do don't have false expectations that a new linux-compatible version will be ever released).

Would you mind waiting some time before archiving this repo, so that people can maybe still comment about possible solutions?
It would be immensely useful for all of us orphans looking for possibilities.

In any case I would suggest adding to the repo description the explanation that you provided to us on your previous comment [here](https://github.com/search5/Evernote-for-Linux/issues/10#issuecomment-2025458845), so that it's clear that the project is no more suitable.

Thank you very much for the great work you have done so far and for giving us the possibility to use evernote on linux!

**Comment by adamOxfordRFERL** [comment]
Just wanted to add my voice to say thank you @search5 for all your work maintaining this project while it was still possible, and explaining the issues around taking it forward. This client has been really appreciated by someone for whom offline access is essential.
