### ISSUE TITLE
Usage documentation wrong?

### ISSUE THREAD

**Issue by timoc** [search5/Evernote-for-Linux#2]
Hi,

I cannot seem to get this working:

```
/publishConfig_update.py --registry http://localhost:4873
Usage: publishConfig_update.py [OPTIONS] REGISTRY
Try 'publishConfig_update.py --help' for help.

Error: no such option: --registry
```

**Comment by search5** [comment]
Are you trying to build Evernote yourself?

The publishConfig_update.py command options have changed a bit.

publishConfig_update.py &lt;verdaccio url&gt; .

It is configured so that it can be built immediately whenever a new version is updated, but compilation may not be smooth depending on the development environment.

Please contact us and we will do our best to help.

**Comment by timoc** [comment]
Not especially, i am trying to run the Linux client natively, so that the global hotkeys work.
